/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MenuPrincipalController;

/**
 *
 * @author tiago
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.controller = new MenuPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelFundoMenuPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuSignUp = new javax.swing.JMenu();
        MenuItemClient = new javax.swing.JMenuItem();
        MenuItemService = new javax.swing.JMenuItem();
        MenuItemUser = new javax.swing.JMenuItem();
        MenuOperation = new javax.swing.JMenu();
        MenuItemSchedule = new javax.swing.JMenuItem();
        MenuReport = new javax.swing.JMenu();
        MenuItemReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelFundoMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/fundo-MenuPrincipal.jpg"))); // NOI18N
        getContentPane().add(LabelFundoMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 1000));

        MenuSignUp.setText("  Cadastro  ");
        MenuSignUp.setActionCommand("Cadastro  ");
        MenuSignUp.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        MenuItemClient.setFont(new java.awt.Font("Circular Std Bold", 1, 18)); // NOI18N
        MenuItemClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/icons/cliente32-icon.png"))); // NOI18N
        MenuItemClient.setText("  Cliente");
        MenuItemClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemClientActionPerformed(evt);
            }
        });
        MenuSignUp.add(MenuItemClient);

        MenuItemService.setFont(new java.awt.Font("Circular Std Bold", 1, 18)); // NOI18N
        MenuItemService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/icons/tesoura32-icon.png"))); // NOI18N
        MenuItemService.setText("  Serviço");
        MenuSignUp.add(MenuItemService);

        MenuItemUser.setFont(new java.awt.Font("Circular Std Bold", 1, 18)); // NOI18N
        MenuItemUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/icons/usuario32-icon.png"))); // NOI18N
        MenuItemUser.setText("  Usuario");
        MenuSignUp.add(MenuItemUser);

        jMenuBar1.add(MenuSignUp);

        MenuOperation.setText("  Operação  ");
        MenuOperation.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        MenuItemSchedule.setFont(new java.awt.Font("Circular Std Bold", 0, 18)); // NOI18N
        MenuItemSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/icons/agenda32-icon.png"))); // NOI18N
        MenuItemSchedule.setText("  Agenda");
        MenuItemSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemScheduleActionPerformed(evt);
            }
        });
        MenuOperation.add(MenuItemSchedule);

        jMenuBar1.add(MenuOperation);

        MenuReport.setText("  Relatório  ");
        MenuReport.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        MenuItemReport.setFont(new java.awt.Font("Circular Std Bold", 0, 18)); // NOI18N
        MenuItemReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/icons/relatorioTrabalho32-icon.png"))); // NOI18N
        MenuItemReport.setText("  Trabalho");
        MenuItemReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemReportActionPerformed(evt);
            }
        });
        MenuReport.add(MenuItemReport);

        jMenuBar1.add(MenuReport);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemClientActionPerformed

    private void MenuItemReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemReportActionPerformed

    private void MenuItemScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemScheduleActionPerformed
        // TODO add your handling code here:
        this.controller.navegarParaAgenda();
    }//GEN-LAST:event_MenuItemScheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFundoMenuPrincipal;
    private javax.swing.JMenuItem MenuItemClient;
    private javax.swing.JMenuItem MenuItemReport;
    private javax.swing.JMenuItem MenuItemSchedule;
    private javax.swing.JMenuItem MenuItemService;
    private javax.swing.JMenuItem MenuItemUser;
    private javax.swing.JMenu MenuOperation;
    private javax.swing.JMenu MenuReport;
    private javax.swing.JMenu MenuSignUp;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
